In [22]:
import tensorflow as tf
import numpy as np
import time

In [2]:
gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)

In [3]:
tf.add(1,2)

<tf.Tensor: id=2, shape=(), dtype=int32, numpy=3>

In [4]:
tf.add([1,2], [3,4])

<tf.Tensor: id=6, shape=(2,), dtype=int32, numpy=array([4, 6])>

In [5]:
tf.square(5)

<tf.Tensor: id=9, shape=(), dtype=int32, numpy=25>

In [6]:
tf.reduce_sum([1,2,3])

<tf.Tensor: id=17, shape=(), dtype=int32, numpy=6>

In [9]:
x = tf.matmul([[1]], [[2,3]])
x

<tf.Tensor: id=25, shape=(1, 2), dtype=int32, numpy=array([[2, 3]])>

In [12]:
ndarray = np.ones([3,3])
tensor = tf.multiply(ndarray, 42)
tensor

<tf.Tensor: id=29, shape=(3, 3), dtype=float64, numpy=
array([[42., 42., 42.],
       [42., 42., 42.],
       [42., 42., 42.]])>

In [13]:
np.add(tensor, 1)

array([[43., 43., 43.],
       [43., 43., 43.],
       [43., 43., 43.]])

In [14]:
tensor.numpy()

array([[42., 42., 42.],
       [42., 42., 42.],
       [42., 42., 42.]])

In [15]:
gpus

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'),
 PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU')]

In [17]:
x = tf.random.uniform([3,3])
x

<tf.Tensor: id=45, shape=(3, 3), dtype=float32, numpy=
array([[0.9455625 , 0.7099714 , 0.76005685],
       [0.32443833, 0.724861  , 0.12018311],
       [0.14027417, 0.00760317, 0.6422045 ]], dtype=float32)>

In [18]:
tf.test.is_gpu_available()

True

In [21]:
x.device

'/job:localhost/replica:0/task:0/device:GPU:0'

In [23]:
def time_matmul(x, num_iter=10):
    start = time.time()
    for i in range(num_iter):
        tf.matmul(x, x)
    elapsed = time.time() - start
    return elapsed / num_iter

In [30]:
mat_size = 1000
num_iter = 10
print(f'Time in milliseconds to multiply {mat_size} square matrix:')
with tf.device('CPU:0'):
    x_cpu = tf.random.uniform([mat_size, mat_size])
    assert x_cpu.device.endswith('CPU:0')
    time_cpu = time_matmul(x_cpu) * 1000
    print(f'CPU: {time_cpu:.3f}')
with tf.device('GPU:0'):
    x_gpu = tf.random.uniform([mat_size, mat_size])
    assert x_gpu.device.endswith('GPU:0')
    time_gpu = time_matmul(x_gpu) * 1000
    print(f'GPU: {time_gpu:6.3f}')    

Time in milliseconds to multiply 1000 square matrix:
CPU: 20.284
GPU:  0.100


In [42]:
ds_tensors = tf.data.Dataset.from_tensor_slices([1,2,3,4,5,6])
print(ds_tensors)
for x in ds_tensors:
    print(x)

<TensorSliceDataset shapes: (), types: tf.int32>
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


In [43]:
# Create a CSV file
import tempfile
_, filename = tempfile.mkstemp()

with open(filename, 'w') as f:
  f.write("""Line 1
Line 2
Line 3
  """)

ds_file = tf.data.TextLineDataset(filename)

In [44]:
ds_tensors2 = ds_tensors.map(tf.square)
print(ds_tensors2)
for x in ds_tensors2:
    print(x)

<MapDataset shapes: (), types: tf.int32>
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(36, shape=(), dtype=int32)


In [46]:
ds_tensors3 = ds_tensors2.shuffle(2).batch(2)
print(ds_tensors3)
for x in ds_tensors3:
    print(x)

<BatchDataset shapes: (None,), types: tf.int32>
tf.Tensor([4 9], shape=(2,), dtype=int32)
tf.Tensor([16  1], shape=(2,), dtype=int32)
tf.Tensor([25 36], shape=(2,), dtype=int32)
