In [3]:
import tensorflow as tf
import numpy as np
keras = tf.keras

In [2]:
gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)

In [4]:
layer = keras.layers.Dense(100)
layer

In [12]:
layer = keras.layers.Dense(units=10, input_shape=(None, 5,))
x = tf.zeros([10,5])
y = layer(x)
y

<tf.Tensor: id=62, shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [15]:
layer.variables

[<tf.Variable 'dense_6/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.15366441, -0.46281925, -0.00162762, -0.35244113,  0.19608349,
         -0.46866912,  0.23200268,  0.08538604, -0.20561081, -0.1266318 ],
        [ 0.5680881 ,  0.15113717, -0.12074906, -0.22260445,  0.11926788,
          0.60247463, -0.3221553 ,  0.0574677 ,  0.37069994,  0.50240535],
        [-0.52731854, -0.5207737 ,  0.38191396,  0.04957449, -0.39884755,
         -0.01254249, -0.2911743 , -0.01181465, -0.18352863, -0.38375944],
        [-0.5988084 , -0.5227    , -0.06355369, -0.00501704, -0.40620697,
          0.17983037, -0.1463941 ,  0.43767482,  0.6216034 , -0.22642905],
        [ 0.19137692,  0.58832735,  0.55252296, -0.53070676, -0.27252167,
         -0.37180442,  0.62286   , -0.21140021,  0.45024413, -0.4070339 ]],
       dtype=float32)>,
 <tf.Variable 'dense_6/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [16]:
layer.kernel

<tf.Variable 'dense_6/kernel:0' shape=(5, 10) dtype=float32, numpy=
array([[-0.15366441, -0.46281925, -0.00162762, -0.35244113,  0.19608349,
        -0.46866912,  0.23200268,  0.08538604, -0.20561081, -0.1266318 ],
       [ 0.5680881 ,  0.15113717, -0.12074906, -0.22260445,  0.11926788,
         0.60247463, -0.3221553 ,  0.0574677 ,  0.37069994,  0.50240535],
       [-0.52731854, -0.5207737 ,  0.38191396,  0.04957449, -0.39884755,
        -0.01254249, -0.2911743 , -0.01181465, -0.18352863, -0.38375944],
       [-0.5988084 , -0.5227    , -0.06355369, -0.00501704, -0.40620697,
         0.17983037, -0.1463941 ,  0.43767482,  0.6216034 , -0.22642905],
       [ 0.19137692,  0.58832735,  0.55252296, -0.53070676, -0.27252167,
        -0.37180442,  0.62286   , -0.21140021,  0.45024413, -0.4070339 ]],
      dtype=float32)>

In [17]:
layer.bias

<tf.Variable 'dense_6/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

In [18]:
class ResnetIdentityBlock(tf.keras.Model):
    def __init__(self, kernel_size, filters):
        super(ResnetIdentityBlock, self).__init__(name='')
        filters1, filters2, filters3 = filters
        
        self.conv2a = tf.keras.layers.Conv2D(filters1, (1,1))
        self.bn2a = tf.keras.layers.BatchNormalization()
        
        self.conv2b = tf.keras.layers.Conv2D(filters2, kernel_size, padding='same')
        self.bn2b = tf.keras.layers.BatchNormalization()
        
        self.conv2c = tf.keras.layers.Conv2D(filters3, (1,1))
        self.bn2c = tf.keras.layers.BatchNormalization()
        
    def call(self, input_tensor, training=False):
        x = self.conv2a(input_tensor)
        x = self.bn2a(x, training=training)
        x = tf.nn.relu(x)
        
        x = self.conv2b(x)
        x = self.bn2b(x, training=training)
        x = tf.nn.relu(x)
        
        x = self.conv2c(x)
        x = self.bn2c(x, training=training)
        
        x += input_tensor
        return tf.nn.relu(x)


In [23]:
block = ResnetIdentityBlock(1, [1,2,3])
x = tf.zeros([1,2,3,3])
y = block(x)

In [24]:
block.summary()

Model: "resnet_identity_block_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_6 (Conv2D)            multiple                  4         
_________________________________________________________________
batch_normalization_6 (Batch multiple                  4         
_________________________________________________________________
conv2d_7 (Conv2D)            multiple                  4         
_________________________________________________________________
batch_normalization_7 (Batch multiple                  8         
_________________________________________________________________
conv2d_8 (Conv2D)            multiple                  9         
_________________________________________________________________
batch_normalization_8 (Batch multiple                  12        
Total params: 41
Trainable params: 29
Non-trainable params: 12
______________________________________________

In [25]:
y

<tf.Tensor: id=319, shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [27]:
my_seq_model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(1, (1,1)),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Conv2D(2, 1, padding='same'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Conv2D(3, (1,1), padding='same'),
    tf.keras.layers.BatchNormalization()
])

In [29]:
y = my_seq_model(x)

In [30]:
my_seq_model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_11 (Conv2D)           multiple                  4         
_________________________________________________________________
batch_normalization_11 (Batc multiple                  4         
_________________________________________________________________
conv2d_12 (Conv2D)           multiple                  4         
_________________________________________________________________
batch_normalization_12 (Batc multiple                  8         
_________________________________________________________________
conv2d_13 (Conv2D)           multiple                  9         
_________________________________________________________________
batch_normalization_13 (Batc multiple                  12        
Total params: 41
Trainable params: 29
Non-trainable params: 12
___________________________________________________________

In [31]:
y

<tf.Tensor: id=551, shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>