In [6]:
# Library imports
import tensorflow as tf
import numpy as np
keras = tf.keras
import matplotlib.pyplot as plt
import os
import sys
import cProfile

In [4]:
# Add src directory to path for local imports
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

# Local imports
from utils import gpu_grow_memory

In [5]:
gpu_grow_memory()

In [7]:
tf.executing_eagerly()

True

In [8]:
x = [[2.0]]
m = tf.matmul(x, x)
print(f'hello.  m = {m}')

hello.  m = [[4.]]


In [9]:
a = tf.constant([[1,2], [3,4]])
print(a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [10]:
b = tf.add(a, 1)
print(b)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [11]:
print(a*b)

tf.Tensor(
[[ 2  6]
 [12 20]], shape=(2, 2), dtype=int32)


In [17]:
def fizzbuzz(max_num):
    counter = tf.constant(0)
    max_num = tf.convert_to_tensor(max_num)
    for num in range(1, max_num.numpy() + 1):
        if int(num % 15) == 0:
            print('FizzBuzz')
        elif int(num % 3) == 0:
            print('Fizz')
        elif int(num % 5) == 0:
            print('Buzz')
        else:
            print(int(num))
        counter += 1

In [18]:
fizzbuzz(15)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz


In [19]:
w = tf.Variable([[1.0]])
with tf.GradientTape() as tape:
    loss = w * w
grad = tape.gradient(loss, w)
print(grad)

tf.Tensor([[2.]], shape=(1, 1), dtype=float32)


In [21]:
(mnist_img, mnist_label), _ = tf.keras.datasets.mnist.load_data()

dataset = tf.data.Dataset.from_tensor_slices(
    (tf.cast(mnist_img[..., tf.newaxis]/255.0, tf.float32),
     tf.cast(mnist_label, tf.int64)))
dataset = dataset.shuffle(1024).batch(32)

In [27]:
model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(16, [3,3], activation='relu', input_shape=(None, None, 1)),
    tf.keras.layers.Conv2D(16, [3,3], activation='relu'),
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(10)
])

In [28]:
for images, labels in dataset.take(1):
    print(f'images[0].shape={images[0].shape}')
    print(f'logits[0]={model(images[0:1]).numpy()}')

images[0].shape=(28, 28, 1)
logits[0]=[[-0.0051801   0.01650383  0.00186019 -0.09211739  0.00935774 -0.0289663
  -0.00483622 -0.04873506  0.01437225 -0.00149763]]
